# Generated by Django 2.2 on 2019-08-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarkManagement', '0002_auto_20190122_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='权重'),
        ),
        migrations.AlterField(
            model_name='titlegroup',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='权重'),
        ),
    ]
