# Generated by Django 2.2 on 2019-12-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MarkManagement', '0003_auto_20190803_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='collegeName',
            field=models.CharField(default='', max_length=20, null=True, verbose_name='学院名称'),
        ),
        migrations.AddField(
            model_name='student',
            name='majorName',
            field=models.CharField(default='', max_length=20, null=True, verbose_name='专业名称'),
        ),
        migrations.AlterField(
            model_name='point',
            name='note',
            field=models.CharField(default='', max_length=400),
        ),
    ]
